### ISSUE TITLE
About gFlex module import issues in FTB-Model

### ISSUE THREAD

**Issue by Cheese-Lvjx** [JoeIbrahim/Yibrahim-IsostasyFTB-Model#1]
Hi guys,
I have some trouble about importing gflex module,Although I have already installed this module,it still shows undefined.I can't find solutions and have trouble in this,Also I'm a new learner . Thanks a lot.
![image](https://github.com/JoeIbrahim/Yibrahim-IsostasyFTB-Model/assets/130534243/9572d9eb-da50-4948-ac24-75077fd535bd)
![image](https://github.com/JoeIbrahim/Yibrahim-IsostasyFTB-Model/assets/130534243/81255e47-d764-42bf-bf52-b80ad0a9901a)

**Comment by JoeIbrahim** [comment]
Hey @Cheese-Lvjx 

I ran these models with Underworld version 2.9 and the GFlex package should already be included with the Underworld installation in that version. I would be surprised if it was removed from the latest version. I'll ask some of the developers and get back to you.

For a quick fix you can run:

`!pip install gflex` 

inside the jupyter notebook itself, before you import GFlex, and it should install it within that environment. 

Otherwise you can try downloading version 2.9 of Underworld through Docker. I have not tested these scripts with the latest version of Underworld so you might run into other issues as well.

Good luck!
Youseph

**Comment by Cheese-Lvjx** [comment]
hi @JoeIbrahim 
I have solved the gflex installation problem thanks to your help！！I am very sorry to bother you again because I have met a new problem，When I run FL2 ，It will report an error below.I tried creating a list and adding each object to the list still didn't work out.
![image](https://github.com/JoeIbrahim/Yibrahim-IsostasyFTB-Model/assets/130534243/f01b3d6c-6371-4450-a58b-9ad05c208f83)
![image](https://github.com/JoeIbrahim/Yibrahim-IsostasyFTB-Model/assets/130534243/a17db6bb-3d65-4e3c-8e49-25d4f22e9e1e)
 
lvjx

**Comment by JoeIbrahim** [comment]
Hey again, you can delete the problematic model.init() on line 20 as we do not need to initialise the model that early and it should get past that point. 

If you're using the latest version of UW you will also have problems with how the tracers are implemented. You can either comment them out to run the models without tracers or you can rewrite that bit of the code for later versions of UW.

Worth noting this that script was run on high performance computing on multiple nodes (usually 192 cpu's). You might have some issues running it on just one cpu related to the mpi rank checks in the GFlex functions. If running locally you will probably also need to decrease the resolution of the model.
